version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../www:/run/www/api
      - ../kuranhocam:/run/www/kuranhocam
      - ./nginx/html:/run/nginx/html # block for production
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d/muallim_backend.conf:/etc/nginx/conf.d/muallim_backend.conf
      - ./nginx/conf.d/muallim_frontend.conf:/etc/nginx/conf.d/muallim_frontend.conf
    command: [nginx-debug, '-g', 'daemon off;']
    links:
      - php
    extra_hosts:
      - "kuranhocam.dev.com:172.18.0.6"
      - "muallimapidev.com:172.18.0.6"
    networks:
      my_network:
        aliases:
          - kuranhocam.dev.com
          - muallimapidev.com
  php:
    build: php
    volumes:
      - ../www:/run/www/api
      - ../kuranhocam:/run/www/kuranhocam
      - ./nginx/html:/run/nginx/html # block for production
      - ./php/${PHP_INI_FILE}:/usr/local/etc/php/php.ini
    ports:
      - 9000:9000
    networks:
      - my_network
  phpcli:
    build: phpcli
    volumes:
      - ../www:/run/www/api
      - ../kuranhocam:/run/www/kuranhocam
    stdin_open: true # docker run -i
    tty: true
    networks:
      - my_network
  mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ../mysql-data:/var/lib/mysql
  redis:
    image: redis:6.0.7

  networks:
    my_network:
      driver: bridge