version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../:/run/www/blogmus
      - ./nginx/html:/run/nginx/html # block for production
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d/blogmus_backend.conf:/etc/nginx/conf.d/blogmus_backend.conf
      - ./nginx/conf.d/blogmus_frontend.conf:/etc/nginx/conf.d/blogmus_frontend.conf
    command: [nginx-debug, '-g', 'daemon off;']
    links:
      - php
  php:
    build: php
    volumes:
      - ../:/run/www/blogmus
      - ./nginx/html:/run/nginx/html # block for production
      - ./php/${PHP_INI_FILE}:/usr/local/etc/php/php.ini
    ports:
      - 9000:9000
  phpcli:
    build: phpcli
    volumes:
      - ../:/run/www/blogmus
    stdin_open: true # docker run -i
    tty: true
  mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ../mysql-data:/var/lib/mysql
  redis:
    image: redis:6.0.7